# Generated by Django 4.1.7 on 2023-02-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0002_remove_incidentsmachine_video_remove_info_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentsmachine',
            name='video_link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='info',
            name='video_link',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
