# Generated by Django 4.1.7 on 2023-02-24 02:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0003_alter_incidentsmachine_video_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentsmachine',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='info',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
