# Generated by Django 4.1.7 on 2023-02-24 02:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0004_alter_incidentsmachine_image_alter_info_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
