# Generated by Django 4.1.7 on 2023-02-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0005_alter_machine_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='info',
            name='title',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='info',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
