# Generated by Django 4.1.7 on 2023-03-14 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_answer_choices_questions_responses_and_more'),
        ('machines', '0006_info_subtitle_info_title_alter_info_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='forms.form'),
        ),
    ]
