# Generated by Django 4.1.7 on 2023-03-21 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_remove_incidentsmachine_machine_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IncidentsMachine',
            new_name='Incidents',
        ),
    ]
