# Generated by Django 4.1.7 on 2023-04-12 14:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_rename_incidentsmachine_incidents'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='epp',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='epp'),
        ),
    ]
