# Generated by Django 4.1.7 on 2023-03-08 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=5000)),
            ],
        ),
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=5000)),
                ('is_answer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=10000)),
                ('question_type', models.CharField(max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('answer_key', models.CharField(blank=True, max_length=5000)),
                ('score', models.IntegerField(blank=True, default=0)),
                ('feedback', models.CharField(max_length=5000, null=True)),
                ('choices', models.ManyToManyField(related_name='choices', to='forms.choices')),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_code', models.CharField(max_length=20)),
                ('responder_ip', models.CharField(max_length=30)),
                ('responder_email', models.EmailField(blank=True, max_length=254)),
                ('responder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responder', to=settings.AUTH_USER_MODEL)),
                ('response', models.ManyToManyField(related_name='response', to='forms.answer')),
            ],
        ),
        migrations.RemoveField(
            model_name='questiondetail',
            name='question',
        ),
        migrations.RemoveField(
            model_name='sectionform',
            name='form',
        ),
        migrations.RemoveField(
            model_name='sectionform',
            name='question',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='form',
        ),
        migrations.RemoveField(
            model_name='userform',
            name='user',
        ),
        migrations.RemoveField(
            model_name='form',
            name='machine',
        ),
        migrations.AddField(
            model_name='form',
            name='allow_view_score',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='form',
            name='authenticated_responder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='background_color',
            field=models.CharField(default='#d9efed', max_length=20),
        ),
        migrations.AddField(
            model_name='form',
            name='code',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='form',
            name='collect_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='confirmation_message',
            field=models.CharField(default='Your response has been recorded.', max_length=10000),
        ),
        migrations.AddField(
            model_name='form',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='form',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='form',
            name='description',
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AddField(
            model_name='form',
            name='edit_after_submit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='is_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='form',
            name='text_color',
            field=models.CharField(default='#272124', max_length=20),
        ),
        migrations.AddField(
            model_name='form',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='form',
            name='updatedAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='AnswerUserForm',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.DeleteModel(
            name='QuestionDetail',
        ),
        migrations.DeleteModel(
            name='SectionForm',
        ),
        migrations.DeleteModel(
            name='UserForm',
        ),
        migrations.AddField(
            model_name='responses',
            name='response_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_to', to='forms.form'),
        ),
        migrations.AddField(
            model_name='answer',
            name='answer_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_to', to='forms.questions'),
        ),
        migrations.AddField(
            model_name='form',
            name='questions',
            field=models.ManyToManyField(related_name='questions', to='forms.questions'),
        ),
    ]
