# Generated by Django 4.1.7 on 2023-03-17 15:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_answer_choices_questions_responses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='questions',
            name='creation_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
