# Generated by Django 4.1.7 on 2023-03-17 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_choices_creation_date_questions_creation_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['-creation_date']},
        ),
    ]
