# Generated by Django 4.1.7 on 2023-03-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0005_alter_questions_feedback'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['creation_date']},
        ),
    ]
