# Generated by Django 4.1.7 on 2023-04-15 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0007_label_alter_choices_options_questions_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
