# Generated by Django 4.1.7 on 2023-03-07 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_achievement_skill_profile_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='specialist',
            field=models.IntegerField(choices=[(0, 'Metalizador'), (1, 'Fresador'), (2, 'Tornero'), (3, 'Supervisor'), (4, 'Administrativo'), (5, 'Jefatura')], default=0),
        ),
    ]
